### ISSUE TITLE
Can't copy

### ISSUE THREAD

**Issue by Its-Alex** [ErenO/Piscine-CPP#1]
T'as envoyé les sous repos git je fait comment pour copier ? 😝

**Comment by ErenO** [comment]
Haha j’avais même pas capté 😂

Le mer. 24 janv. 2018 à 17:54, Alexandre M <notifications@github.com> a
écrit :

**Comment by Its-Alex** [comment]
Fait gaffe tu l'as fais dans plein de tes repos :)
